### ISSUE TITLE
Fix failing unit tests

### ISSUE THREAD

**Issue by justb4** [meggsimum/wegue#180]
The following unit tests are failing (for me). Version is `master` as on feb 24 2021:

```
1) "before each" hook for "has correct default props"
     helpwin/HelpWin.vue props
     TypeError: Cannot read property 'windowTitle' of undefined
    at VueComponent.data (webpack:///src/components/helpwin/HelpWin.vue:40:1 <- index.js:114854:86)
    at getData (webpack:///~/vue/dist/vue.esm.js:4757:1 <- index.js:7847:17)
    at initData (webpack:///~/vue/dist/vue.esm.js:4714:1 <- index.js:7804:7)
    at initState (webpack:///~/vue/dist/vue.esm.js:4651:1 <- index.js:7741:5)
    at VueComponent.Vue._init (webpack:///~/vue/dist/vue.esm.js:5015:1 <- index.js:8105:5)
    at new VueComponent (webpack:///~/vue/dist/vue.esm.js:5163:1 <- index.js:8253:12)
    at createComponentInstanceForVnode (webpack:///~/vue/dist/vue.esm.js:3292:1 <- index.js:6382:10)
    at init (webpack:///~/vue/dist/vue.esm.js:3123:1 <- index.js:6213:45)
    at createComponent (webpack:///~/vue/dist/vue.esm.js:5989:1 <- index.js:9079:9)
    at createElm (webpack:///~/vue/dist/vue.esm.js:5936:1 <- index.js:9026:9)

2) "before each" hook for "has correct default data"
     helpwin/HelpWin.vue data
     TypeError: Cannot read property 'windowTitle' of undefined
    at VueComponent.data (webpack:///src/components/helpwin/HelpWin.vue:40:1 <- index.js:114854:86)
    at getData (webpack:///~/vue/dist/vue.esm.js:4757:1 <- index.js:7847:17)
    at initData (webpack:///~/vue/dist/vue.esm.js:4714:1 <- index.js:7804:7)
    at initState (webpack:///~/vue/dist/vue.esm.js:4651:1 <- index.js:7741:5)
    at VueComponent.Vue._init (webpack:///~/vue/dist/vue.esm.js:5015:1 <- index.js:8105:5)
    at new VueComponent (webpack:///~/vue/dist/vue.esm.js:5163:1 <- index.js:8253:12)
    at createComponentInstanceForVnode (webpack:///~/vue/dist/vue.esm.js:3292:1 <- index.js:6382:10)
    at init (webpack:///~/vue/dist/vue.esm.js:3123:1 <- index.js:6213:45)
    at createComponent (webpack:///~/vue/dist/vue.esm.js:5989:1 <- index.js:9079:9)
    at createElm (webpack:///~/vue/dist/vue.esm.js:5936:1 <- index.js:9026:9)

3) "before each" hook for "onWinXClose switches show"
     helpwin/HelpWin.vue methods
     TypeError: Cannot read property 'windowTitle' of undefined
    at VueComponent.data (webpack:///src/components/helpwin/HelpWin.vue:40:1 <- index.js:114854:86)
    at getData (webpack:///~/vue/dist/vue.esm.js:4757:1 <- index.js:7847:17)
    at initData (webpack:///~/vue/dist/vue.esm.js:4714:1 <- index.js:7804:7)
    at initState (webpack:///~/vue/dist/vue.esm.js:4651:1 <- index.js:7741:5)
    at VueComponent.Vue._init (webpack:///~/vue/dist/vue.esm.js:5015:1 <- index.js:8105:5)
    at new VueComponent (webpack:///~/vue/dist/vue.esm.js:5163:1 <- index.js:8253:12)
    at createComponentInstanceForVnode (webpack:///~/vue/dist/vue.esm.js:3292:1 <- index.js:6382:10)
    at init (webpack:///~/vue/dist/vue.esm.js:3123:1 <- index.js:6213:45)
    at createComponent (webpack:///~/vue/dist/vue.esm.js:5989:1 <- index.js:9079:9)
    at createElm (webpack:///~/vue/dist/vue.esm.js:5936:1 <- index.js:9026:9)

4) "before each" hook for "has correct default props"
     helpwin/ToggleButton.vue props
     TypeError: Cannot read property 'on' of undefined
    at Object.fn [as activator] (webpack:///src/components/helpwin/ToggleButton.vue?6e9e:13:1 <- index.js:174273:26)
    at webpack:///~/@vue/test-utils/dist/vue-test-utils.js:2395:68 <- index.js:17485:125
    at Array.map (<anonymous>)
    at Proxy.render (webpack:///~/@vue/test-utils/dist/vue-test-utils.js:2395:1 <- index.js:17485:50)
    at VueComponent.Vue._render (webpack:///~/vue/dist/vue.esm.js:3557:1 <- index.js:6647:22)
    at VueComponent.updateComponent (webpack:///~/vue/dist/vue.esm.js:4075:1 <- index.js:7165:21)
    at Watcher.get (webpack:///~/vue/dist/vue.esm.js:4488:1 <- index.js:7578:25)
    at new Watcher (webpack:///~/vue/dist/vue.esm.js:4477:1 <- index.js:7567:12)
    at mountComponent (webpack:///~/vue/dist/vue.esm.js:4082:1 <- index.js:7172:3)
    at VueComponent.Vue.$mount (webpack:///~/vue/dist/vue.esm.js:9063:1 <- index.js:12153:10)

5) "before each" hook for "has correct default data"
     helpwin/ToggleButton.vue data
     TypeError: Cannot read property 'on' of undefined
    at Object.fn [as activator] (webpack:///src/components/helpwin/ToggleButton.vue?6e9e:13:1 <- index.js:174273:26)
    at webpack:///~/@vue/test-utils/dist/vue-test-utils.js:2395:68 <- index.js:17485:125
    at Array.map (<anonymous>)
    at Proxy.render (webpack:///~/@vue/test-utils/dist/vue-test-utils.js:2395:1 <- index.js:17485:50)
    at VueComponent.Vue._render (webpack:///~/vue/dist/vue.esm.js:3557:1 <- index.js:6647:22)
    at VueComponent.updateComponent (webpack:///~/vue/dist/vue.esm.js:4075:1 <- index.js:7165:21)
    at Watcher.get (webpack:///~/vue/dist/vue.esm.js:4488:1 <- index.js:7578:25)
    at new Watcher (webpack:///~/vue/dist/vue.esm.js:4477:1 <- index.js:7567:12)
    at mountComponent (webpack:///~/vue/dist/vue.esm.js:4082:1 <- index.js:7172:3)
    at VueComponent.Vue.$mount (webpack:///~/vue/dist/vue.esm.js:9063:1 <- index.js:12153:10)

6) has correct default data
     ol/Map.vue data
     AssertionError: expected undefined to deeply equal { code: 'EPSG:3857', units: 'm' }
    at Context.<anonymous> (webpack:///test/unit/specs/components/ol/Map.spec.js:65:37 <- index.js:129371:37)

7) Setup permalinkController
     ol/Map.vue data - PermalinkController successfully setup
     AssertionError: expected 4 to equal 2
    at Context.<anonymous> (webpack:///test/unit/specs/components/ol/PermalinkController.spec.js:83:63 <- index.js:129741:63)

8) Layer Listeners are (re)created when the layer stack changes
     ol/Map.vue data - PermalinkController successfully setup
     AssertionError: expected 4 to equal 2
    at Context.<anonymous> (webpack:///test/unit/specs/components/ol/PermalinkController.spec.js:91:63 <- index.js:129749:63)

9) Setup and apply permalinkController - apply from document.location.hash
     ol/Map.vue data - PermalinkController applied from document.location.hash/search
     AssertionError: expected 4 to equal 2
    at Context.<anonymous> (webpack:///test/unit/specs/components/ol/PermalinkController.spec.js:153:58 <- index.js:129811:58)

```

Several errors deal with `HelpWin`: mismatch between expected and provided config, can/should be fixed in the test spec file. 
Others may be caused by config changes like Layers. Need to dive into.

**Comment by chrismayer** [comment]
Closed by #182
